### ISSUE TITLE
Go Back Button is Behind Text

### ISSUE THREAD

**Issue by kevin07696** [SarahChoung/website#3]
Hi Sarah, I saw your website on LinkedIn and it looks amazing, but I noticed this. I hope this helps.
![Screenshot from 2020-09-03 00-26-39](https://user-images.githubusercontent.com/32726219/92071533-f461d000-ed7c-11ea-95ed-e67a36557948.png)
![Screenshot from 2020-09-03 00-33-06](https://user-images.githubusercontent.com/32726219/92071573-11969e80-ed7d-11ea-867e-63f55a488991.png)

**Comment by SarahChoung** [comment]
Oof, that's embarrassing. Thank you so much for the catch!

**Comment by SarahChoung** [comment]
Hrm, I'm trying to fix the problem, but this is what I see on my end

![Screen Shot 2020-09-03 at 9 53 54 PM](https://user-images.githubusercontent.com/60276373/92200980-2849fd80-ee30-11ea-91de-256618ad2c18.png)
![Screen Shot 2020-09-03 at 9 54 25 PM](https://user-images.githubusercontent.com/60276373/92200985-2a13c100-ee30-11ea-86c8-d587c3a6243b.png)

**Comment by kevin07696** [comment]
Yeah, I'm not too sure about that either it looks fine on my phone. I'll close this issue for now.
